language: cpp
sudo: enabled
services:
- docker
stages:
- test
jobs:
  include:
    stage: test
    install:
      - sudo docker pull slocomptech/docker-arduino:latest
      - sudo docker run -it -d --name buildenv slocomptech/docker-arduino bash
      - sudo docker ps
    before_script:
      - sudo docker exec buildenv git clone -b ${TRAVIS_BRANCH} https://github.com/SloCompTech/ByteConvert_arduino.git ByteConvert_arduino
      - sudo docker exec buildenv bash -c 'echo "arduino:avr:uno" >> arduino_platforms.txt && echo "arduino:avr:mega:cpu=atmega2560" >> arduino_platforms.txt && echo "arduino:avr:nano:cpu=atmega328" >> arduino_platforms.txt && echo "arduino:avr:mini:cpu=atmega328" >> arduino_platforms.txt && echo "arduino:avr:micro" >> arduino_platforms.txt'
    script:
      - sudo docker exec buildenv bash -c 'arduino_build_lib ByteConvert_arduino'
    after_script:
      - sudo docker stop buildenv
      - sudo docker rm buildenv
      - sudo docker rmi slocomptech/docker-arduino:latest
      - sudo docker ps -a